server:
  port: 8081

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

msa:
  api-url: ${MSA_API_URL}


